apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: f52jqfs09-go-gitops
  description: This is GitOps manifest for f52jqfs09-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: f52jqfs09-go
    janus-idp.io/tekton: f52jqfs09-go
    backstage.io/kubernetes-id: f52jqfs09-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:f52jqfs09-go
